/*
* generated by Xtext
*/
package eu.hohenegger.template.parser;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class JSONUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return eu.hohenegger.template.parser.ui.internal.JSONActivator.getInstance().getInjector("eu.hohenegger.template.parser.JSON");
	}
	
}
