/*
 * generated by Xtext
 */
package eu.hohenegger.template.parser;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class JSONRuntimeModule extends eu.hohenegger.template.parser.AbstractJSONRuntimeModule {

}
