/*
* generated by Xtext
*/
package eu.hohenegger.template.parser;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class JSONStandaloneSetup extends JSONStandaloneSetupGenerated{

	public static void doSetup() {
		new JSONStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

