/*
* generated by Xtext
*/
package eu.hohenegger.template.parser.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import eu.hohenegger.template.parser.services.JSONGrammarAccess;

public class JSONParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private JSONGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS");
	}
	
	@Override
	protected eu.hohenegger.template.parser.parser.antlr.internal.InternalJSONParser createParser(XtextTokenStream stream) {
		return new eu.hohenegger.template.parser.parser.antlr.internal.InternalJSONParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "JObject";
	}
	
	public JSONGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(JSONGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
