/*
 * generated by Xtext
 */
package eu.hohenegger.template.parser.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class JSONUiModule extends eu.hohenegger.template.parser.ui.AbstractJSONUiModule {
	public JSONUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
