/**
 * generated by Xtext
 */
package eu.hohenegger.template.parser.validation;

import eu.hohenegger.template.parser.validation.AbstractJSONValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class JSONValidator extends AbstractJSONValidator {
}
