/*
 * generated by Xtext
 */
package eu.hohenegger.template.parser.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractJSONValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(eu.hohenegger.template.parser.jSON.JSONPackage.eINSTANCE);
		return result;
	}
}
