/**
 * generated by Xtext
 */
package eu.hohenegger.template.parser.ui.contentassist;

import eu.hohenegger.template.parser.ui.contentassist.AbstractJSONProposalProvider;

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
@SuppressWarnings("all")
public class JSONProposalProvider extends AbstractJSONProposalProvider {
}
